# Generated by Django 3.0.8 on 2020-07-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions2',
            field=models.IntegerField(default=0),
        ),
    ]
