# Generated by Django 3.0.8 on 2020-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=600)),
                ('option1', models.CharField(max_length=600)),
                ('option2', models.CharField(max_length=600)),
                ('option3', models.CharField(max_length=600)),
                ('option4', models.CharField(max_length=600)),
                ('answer', models.CharField(max_length=600)),
            ],
        ),
    ]
