# Generated by Django 3.0.8 on 2020-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
    ]
