# Generated by Django 3.0.8 on 2020-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200726_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='TimeDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
    ]
