# Generated by Django 3.0.8 on 2020-07-23 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_questions_addedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=600)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('max_marks', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('AddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
